# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
APPLY_FIXES_EVENT: all # all, push, pull_request, none (use none in case of use of Updated sources reporter)
APPLY_FIXES_MODE: pull_request # create a new commit and push it on the same branch, or pull_request to create a new PR targeting the branch.
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - SPELL # Uncomment to disable checks of spelling mistakes
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: true
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass

FILTER_REGEX_EXCLUDE: (lib/)

PRE_COMMANDS:
  - command: npm install eslint-plugin-i18next@latest
    cwd: "root" # Will be run at the root of MegaLinter docker image

DISABLE_ERRORS: true
UPDATED_SOURCES_REPORTER: false