# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - SPELL # Uncomment to disable checks of spelling mistakes
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: true
DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass

FILTER_REGEX_EXCLUDE: (lib/)

PRE_COMMANDS:
  - command: npm install eslint-plugin-i18next@latest
    cwd: "root" # Will be run at the root of MegaLinter docker image

UPDATED_SOURCES_REPORTER: false